DROP TABLE IF EXISTS TBL_AUTH;
CREATE TABLE IF NOT EXISTS TBL_AUTH(
  AUTH TINYINT(4) NOT NULL PRIMARY KEY,
  AUTHNM VARCHAR(100) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO TBL_AUTH VALUES ('1','통합관리자');
INSERT INTO TBL_AUTH VALUES ('2','통합관리자2');
INSERT INTO TBL_AUTH VALUES ('3','통합관리자3');
INSERT INTO TBL_AUTH VALUES ('4','통합관리자4');
INSERT INTO TBL_AUTH VALUES ('5','통합관리자5');
INSERT INTO TBL_AUTH VALUES ('6','통합관리자6');
INSERT INTO TBL_AUTH VALUES ('7','통합관리자7');
INSERT INTO TBL_AUTH VALUES ('8','통합관리자8');
INSERT INTO TBL_AUTH VALUES ('9','통합관리자9');

DROP TABLE IF EXISTS TBL_ADMIN;
CREATE TABLE IF NOT EXISTS TBL_ADMIN(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERID VARCHAR(50) NOT NULL UNIQUE,
  USERNM VARCHAR(50) NOT NULL,
  PWD    VARCHAR(20) NOT NULL,
  EMAIL  VARCHAR(150) NOT NULL,
  TEL    VARCHAR(13) NOT NULL,
  HP     VARCHAR(13) NOT NULL,
  AUTH   TINYINT(4) NOT NULL,
  MDATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE TBL_ADMIN ADD FOREIGN KEY ( AUTH ) REFERENCES TBL_AUTH(AUTH) ON DELETE CASCADE ON UPDATE CASCADE;

/* 트리거는 안써도 아래의 INSERT 문과 같이 NULL로 입력하면 자동으로 오늘 날자가 입력된다 
CREATE
    TRIGGER TBL_ADMIN_OnInsert BEFORE INSERT
            ON TBL_ADMIN FOR EACH ROW
    SET
        NEW.WDATE = NOW()
;
*/
-- INSERT INTO TBL_ADMIN ( INTNUM,USERID,USERNM,PWD,EMAIL,TEL,HP,AUTH,WDATE ) VALUES ( '','admin','관리자','1','jcc2713@jcccom.co.kr','02-3443-2631','','1', NULL );
INSERT INTO TBL_ADMIN ( INTNUM,USERID,USERNM,PWD,EMAIL,TEL,HP,AUTH,WDATE ) VALUES ( '','master','관리자','lifejcc2015','jcc2713@jcccom.co.kr','02-3443-2631','','1', NULL );
INSERT INTO TBL_ADMIN ( INTNUM,USERID,USERNM,PWD,EMAIL,TEL,HP,AUTH,WDATE ) VALUES ( '','parkpy','박필용','lifejcc2015','jcc2713@jcccom.co.kr','02-3443-2631','','1', NULL );
INSERT INTO TBL_ADMIN ( INTNUM,USERID,USERNM,PWD,EMAIL,TEL,HP,AUTH,WDATE ) VALUES ( '','hwangkiyel','황기열','lifejcc2015','jcc2713@jcccom.co.kr','02-3443-2631','','1', NULL );


DROP TABLE IF EXISTS TBL_XLS_UPLOAD_ATTACH;
CREATE TABLE IF NOT EXISTS TBL_XLS_UPLOAD_ATTACH(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  XLSNM  VARCHAR(150) NOT NULL COMMENT '엑셀업로드명',
  RXLSNM  VARCHAR(150) NOT NULL COMMENT '서버에저장된엑셀업로드명',
  XSIZE   VARCHAR(50) NOT NULL COMMENT'사이즈',
  MIME   VARCHAR(100) NOT NULL COMMENT '마임타입',
  GUBUN CHAR(1) DEFAULT '0' NOT NULL COMMENT'구입:0,이벤트:1',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS TBL_XLS_UPLOAD;
CREATE TABLE IF NOT EXISTS TBL_XLS_UPLOAD(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RADDR  VARCHAR(250) COMMENT '받는분 주소',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  RTELETC VARCHAR(20) COMMENT '받는사람기타연락처',
  ORDERNUM   VARCHAR(50) COMMENT '고객주문번호',
  ITEMCODE   VARCHAR(50) COMMENT '품목코드',
  ITEM   VARCHAR(250) COMMENT '품목명',
  CNT    VARCHAR(20) COMMENT '내품수량',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  MSG1    VARCHAR(100) COMMENT '배송메세지1',
  MSG2    VARCHAR(100) COMMENT '배송메세지2',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS TBL_XLS_UPLOAD_DB;
CREATE TABLE IF NOT EXISTS TBL_XLS_UPLOAD_DB(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RADDR  VARCHAR(250) COMMENT '받는분 주소',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  RTELETC VARCHAR(20) COMMENT '받는사람기타연락처',
  ORDERNUM   VARCHAR(50) COMMENT '고객주문번호',
  ITEMCODE   VARCHAR(50) COMMENT '품목코드',
  ITEM   VARCHAR(250) COMMENT '품목명',
  CNT    VARCHAR(20) COMMENT '내품수량',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  MSG1    VARCHAR(100) COMMENT '배송메세지1',
  MSG2    VARCHAR(100) COMMENT '배송메세지2',
  SYN    CHAR(1) COMMENT '발송여부 0:미발송 1:발송',
  SDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '발송일',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 발송여부는  ( QR 코드 생성함과 동시에 발송으로 판단하기로 함. 20150416 황기열 차장결정  )


-- 이벤트 DB
DROP TABLE IF EXISTS TBL_EVNT_UPLOAD;
CREATE TABLE IF NOT EXISTS TBL_EVNT_UPLOAD(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UPDAY  VARCHAR(10) COMMENT '업로드일자',
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  SEMAIL  VARCHAR(150) COMMENT '주문자 이메일',
  EVNTDAY VARCHAR(10) COMMENT '기념일',
  EVNTCONT VARCHAR(1000) COMMENT '기념일 내용',
  URL    VARCHAR(350) COMMENT '동영상 URL',
  ISPUBLIC  VARCHAR(10)  COMMENT '공개여부',
  ACESS  VARCHAR(50)  COMMENT '접근경로',
  UPDAYTIME  VARCHAR(50) COMMENT'등록시간',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;;

DROP TABLE IF EXISTS TBL_EVNT_UPLOAD_DB;
CREATE TABLE IF NOT EXISTS TBL_EVNT_UPLOAD_DB(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UPDAY  VARCHAR(10) COMMENT '업로드일자',
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  SEMAIL  VARCHAR(150) COMMENT '주문자 이메일',
  EVNTDAY VARCHAR(10) COMMENT '기념일',
  EVNTCONT VARCHAR(1000) COMMENT '기념일 내용',
  URL    VARCHAR(350) COMMENT '동영상 URL',
  ISPUBLIC  VARCHAR(10)  COMMENT '공개여부',
  ACESS  VARCHAR(50)  COMMENT '접근경로',
  UPDAYTIME  VARCHAR(50) COMMENT'등록시간',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP VIEW IF EXISTS VW_UPLOAD_DATA;
CREATE OR REPLACE VIEW VW_UPLOAD_DATA
AS
SELECT INTNUM,RNAME,  RADDR,RTEL,   RTELETC,   ORDERNUM,  ITEMCODE,    ITEM,   CNT,SNAME,STEL,MSG1,MSG2,SYN,'' URL,SDATE, WDATE
FROM TBL_XLS_UPLOAD_DB
WHERE INTNUM NOT IN (
                      SELECT A.INTNUM
		      FROM TBL_XLS_UPLOAD_DB A
		           INNER JOIN TBL_EVNT_UPLOAD_DB B ON A.RNAME=B.RNAME AND A.RTEL=B.RTEL AND A.SNAME=B.SNAME AND A.STEL=B.STEL
	              WHERE A.INTNUM IS NOT NULL
      )
UNION 
SELECT INTNUM,RNAME,'' RADDR,RTEL,'' RTELETC,'' ORDERNUM,'' ITEMCODE,'' ITEM,'' CNT,SNAME,STEL,'' MSG1,'' MSG2,'' SYN,URL,'' SDATE, WDATE
FROM TBL_EVNT_UPLOAD_DB
WHERE INTNUM NOT IN (
                      SELECT B.INTNUM
		      FROM TBL_XLS_UPLOAD_DB A
		           INNER JOIN TBL_EVNT_UPLOAD_DB B ON A.RNAME=B.RNAME AND A.RTEL=B.RTEL AND A.SNAME=B.SNAME AND A.STEL=B.STEL
	              WHERE A.INTNUM IS NOT NULL
      );




-- 구매자 ( 변경하기로 함 20150423 오후 4시)
/*
DROP TABLE IF EXISTS TBL_XLS_UPLOAD;
CREATE TABLE IF NOT EXISTS TBL_XLS_UPLOAD(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UPDAY  VARCHAR(10) COMMENT '업로드 일자',
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RADDR  VARCHAR(250) COMMENT '받는분 주소',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  ITEM   VARCHAR(250) COMMENT '품목명',
  CNT    VARCHAR(20) COMMENT '내품수량',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- 엑셀 업로드 후 이름과 주민번호가 UNIQUE 한 것만 넣는다.
DROP TABLE IF EXISTS TBL_XLS_UPLOAD_DB;
CREATE TABLE IF NOT EXISTS TBL_XLS_UPLOAD_DB(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UPDAY  VARCHAR(10) COMMENT '업로드 일자',
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RADDR  VARCHAR(250) COMMENT '받는분 주소',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  ITEM   VARCHAR(250) COMMENT '품목명',
  CNT    VARCHAR(20) COMMENT '내품수량',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  SYN    CHAR(1) COMMENT '발송여부 0:미발송 1:발송',
  SDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '발송일',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 발송여부는  ( QR 코드 생성함과 동시에 발송으로 판단하기로 함. 20150416 황기열 차장결정  )


-- 이벤트 DB
DROP TABLE IF EXISTS TBL_EVNT_UPLOAD;
CREATE TABLE IF NOT EXISTS TBL_EVNT_UPLOAD(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  URL    VARCHAR(350) COMMENT '동영상 URL',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;;

DROP TABLE IF EXISTS TBL_EVNT_UPLOAD_DB;
CREATE TABLE IF NOT EXISTS TBL_EVNT_UPLOAD_DB(
  INTNUM MEDIUMINT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RNAME  VARCHAR(50) COMMENT '받는분 이름',
  RTEL   VARCHAR(20) COMMENT '받는사람 전화번호',
  SNAME  VARCHAR(50) COMMENT '주문자 성명',
  STEL   VARCHAR(20) COMMENT '주문자 전화번호',
  URL    VARCHAR(350) COMMENT '동영상 URL',
  WDATE  TIMESTAMP DEFAULT '0000-00-00 00:00:00'  NOT NULL COMMENT '등록일'
)ENGINE=MyISAM DEFAULT CHARSET=utf8;
*/

/*
DROP VIEW IF EXISTS VW_UPLOAD_DATA;
CREATE OR REPLACE VIEW VW_UPLOAD_DATA
AS
SELECT A.INTNUM,A.UPDAY,A.RNAME,A.RADDR,A.RTEL,A.ITEM,A.CNT,A.SNAME,A.STEL,A.SYN,URL,A.WDATE
FROM TBL_XLS_UPLOAD_DB A 
     LEFT OUTER JOIN TBL_EVNT_UPLOAD_DB B ON ( A.RNAME=B.RNAME AND A.RTEL=B.RTEL ) AND ( A.SNAME=B.SNAME AND A.STEL=B.STEL )  
WHERE B.INTNUM IS NULL

UNION

SELECT B.INTNUM,A.UPDAY,A.RNAME,A.RADDR,A.RTEL,A.ITEM,A.CNT,A.SNAME,A.STEL,'0' SYN,URL,B.WDATE
FROM TBL_XLS_UPLOAD_DB A 
     RIGHT OUTER JOIN TBL_EVNT_UPLOAD_DB B ON ( A.RNAME=B.RNAME AND A.RTEL=B.RTEL ) AND ( A.SNAME=B.SNAME AND A.STEL=B.STEL )  
WHERE A.INTNUM IS NULL;

DROP VIEW IF EXISTS VW_UPLOAD_DATA;
CREATE OR REPLACE VIEW VW_UPLOAD_DATA
AS
SELECT INTNUM,UPDAY,RNAME,RADDR,RTEL,ITEM,CNT,SNAME,STEL,SYN,'' URL,WDATE
FROM TBL_XLS_UPLOAD_DB
WHERE INTNUM NOT IN (
                      SELECT A.INTNUM
		      FROM TBL_XLS_UPLOAD_DB A
		           INNER JOIN TBL_EVNT_UPLOAD_DB B ON A.RNAME=B.RNAME AND A.RTEL=B.RTEL AND A.SNAME=B.SNAME AND A.STEL=B.STEL
	              WHERE A.INTNUM IS NOT NULL
      )
UNION 
SELECT INTNUM,'' UPDAY,RNAME,'' RADDR,RTEL,'' ITEM,'' CNT,SNAME,STEL,'' SYN,URL,WDATE
FROM TBL_EVNT_UPLOAD_DB
WHERE INTNUM NOT IN (
                      SELECT B.INTNUM
		      FROM TBL_XLS_UPLOAD_DB A
		           INNER JOIN TBL_EVNT_UPLOAD_DB B ON A.RNAME=B.RNAME AND A.RTEL=B.RTEL AND A.SNAME=B.SNAME AND A.STEL=B.STEL
	              WHERE A.INTNUM IS NOT NULL
      );

*/